#!/usr/bin/env sh

npx lint-staged
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "Lint-staged failed. Please fix linting/formatting issues before committing"
  exit 1
fi

if git diff --cached --quiet; then
  echo ""
  echo "No changes after lint-staged."
  exit 1
else
  echo ""
  echo "Changes after lint-staged successfully added to commit."
  exit 0
fi